### ISSUE TITLE
Can't disable dummy login

### ISSUE THREAD

**Issue by xarem** [mirego/accent#153]
Hi all

Thanks for open-sourcing this great piece of software!

I'm deploying accent with a docker-compose file and I'm trying to add Google auth. This works as expected but the dummy login is still available. 

If I check the env vars in the container, it looks good: 

```
$ docker exec -it accent env
[...]
DUMMY_LOGIN_ENABLED=0
GOOGLE_API_CLIENT_ID=**********.apps.googleusercontent.com
GOOGLE_API_CLIENT_SECRET=**********
[...]
```

Thank you for your support.

## Screenshot:

![image](https://user-images.githubusercontent.com/647483/76867132-67c26480-6865-11ea-8d73-38ed8e12b5ea.png)

## docker-compose.yml
```yml
version: '3.4'
services:
    accent:
        image: "mirego/accent"
        environment:
            VIRTUAL_HOST: **********.dev
            VIRTUAL_PORT: 4000
            PORT: 4000
            DATABASE_URL: "postgres://postgres@accent_postgresql:5432/accent"
            API_HOST: "https://**********.dev"
            WEBAPP_URL: "https://**********.dev"
            RESTRICTED_DOMAIN: "whatwedo.ch"
            DUMMY_LOGIN_ENABLED: 0
            GOOGLE_API_CLIENT_ID: "**********.apps.googleusercontent.com"
            GOOGLE_API_CLIENT_SECRET: "**********"
            MAILER_FROM: accent@whatwedo.ch
            SMTP_ADDRESS: smtp.mailchannels.net
            SMTP_PORT: 25
            SMTP_USERNAME: whatwedo
            SMTP_PASSWORD: **********
        expose:
            - "4000"
        depends_on:
            - accent_postgresql
        restart: always
        hostname: accent
        container_name: accent
        networks:
            - default
            - reverseproxy

    accent_postgresql:
        image: postgres:10.3
        environment:
            - POSTGRES_DB=accent
        volumes:
            - /var/lib/accent_postgresql/data:/var/lib/postgresql/data
        restart: always
        hostname: accent_postgresql
        container_name: accent_postgresql
        networks:
            - default
            - reverseproxy

networks:
    reverseproxy:
        external: true
```
