### ISSUE TITLE
Plural forms in rails serializer

### ISSUE THREAD

**Issue by stefkin** [mirego/accent#156]
I have an issue similar to #30 .
It seems to be fixed for gettext serializer but the is still reproducible in rails serializer and probably others.

Steps to reproduce:

You can upload the file to a new project with english master lang

```
---
en:
  months:
    one: month
    other: months
```

then add russian language and upload the following via add translations

```
---
ru:
  months:
    many: месяцев
    few: месяца
    one: месяц
    other: месяцев
```

An export of russian translations will look like:

```
"ru":
  "months":
    "one": "месяц"
    "other": "месяцев"
```

All the plural forms which aren't present in master language are missing
