### ISSUE TITLE
Database clears itself

### ISSUE THREAD

**Issue by RappyTV** [mirego/accent#395]
So, I run an accent instance using docker-compose and I have this weird bug that every now and then the database just get's cleared. I am not doing anything I just have a cronjob (every 6 hours) for my discord bots to pull the new translations.
This is what it looks like after bug happened (that's the second time now):
![image](https://github.com/mirego/accent/assets/72705182/e9730c02-6a9f-46c4-a1c0-90eeac629db3)
This is the docker-compose.yml
```yml
version: '3.7'

services:

  application:
    image: mirego/accent
    container_name: accent
    restart: unless-stopped
    build: .
    ports:
      - 4000:4000
    depends_on:
      - postgresql
    environment:
      - PORT=4000
      - DATABASE_URL=postgres://postgres@REDACTED:5433/accent_development
      - CANONICAL_URL=http://translate.rappytv.com
      - RESTRICTED_PROJECT_CREATOR_EMAIL_DOMAIN=rappytv.com
      - DISCORD_CLIENT_ID=1106918372521803848
      - DISCORD_CLIENT_SECRET=REDACTED
      - MAILER_FROM=lang@rappytv.com
      - SMTP_ADDRESS=mail.rappytv.com
      - SMTP_POST=587
      - SMTP_USERNAME=lang@rappytv.com
      - SMTP_PASSWORD=REDACTED

  postgresql:
    image: postgres:10.3
    container_name: accent-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=accent_development
    ports:
      - 5433:5432
    volumes:
      - accent_psql:/var/lib/postgresql/data

volumes:
  accent_psql:
```
The `docker-compose logs` (that's not the full log as it continues for 20k+ lines):
https://media.rappytv.com/u/9niqrP.txt
I know that there are some bearer tokens in the log but the projects are gone (after a restart) anyway so idc
