### ISSUE TITLE
Increase tolerance for Yaml files or increase tolerance for Yaml types

### ISSUE THREAD

**Issue by BingYanchi** [mirego/accent#425]
In [Spigot](https://www.spigotmc.org/), the default supported Yaml format is not the common Yaml format.

Them does not meet any of the four requirements for Yaml format.

Many programs use non-standard yaml formats, which makes it impossible to use Accent to localize them.

Example:

```yaml
gui-area-title: "%queueDisplayName%"
#%serverName% - Raw server name
#%serverDisplayName% - Display name of the server
#%serverMotd% - MOTD of the server
#%serverPlayerNum% - Now players number of the server
#%serverMaxPlayerNum% - Max players number of the server
gui-area-match-server-name: "&a%serverDisplayName%"
gui-area-match-server-description: |-
  &8%queueDisplayName%

  &7Current player: &a%serverPlayerNum%&7 / &a%serverMaxPlayerNum%
  &7Current status: &a%serverMotd%

  &eClick to play
```
