### ISSUE TITLE
Can't login in newly setup accent service

### ISSUE THREAD

**Issue by FuckingToasters** [mirego/accent#444]
Hello, so here is my docker compose file:

```yml
services:
  postgres-zipline:
    container_name: postgres-zipline
    image: postgres:15
    networks:
      - revproxy
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=FhKCi1jMGqDJhgqjYXigf8A7yup5adn4O
      - POSTGRES_DATABASE=postgres
    volumes:
      - zipline_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-accent:
    container_name: postgres-accent
    image: postgres:15.6
    networks:
      - revproxy
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mB56g5FQMiCLzrquSae4znUHxIqp1Y91B
      - POSTGRES_DATABASE=accent_development
    volumes:
      - accent_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  zipline:
    container_name: zipline
    image: ghcr.io/diced/zipline
    networks:
      - revproxy
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - MFA_TOTP_ENABLED=true
      - WEBSITE_SHOW_FILES_PER_USER=true
      - WEBSITE_TITLE=InfityHost
      - CORE_RETURN_HTTPS=false
      - CORE_SECRET=faeu9uvieJuPVLg38zghRi
      - CORE_DATABASE_URL=postgres://postgres:FhKCi1jMGqDJhgqjYXigf8A7yup5adn4O@postgres-zipline/postgres
      - CORE_LOGGER=true
    volumes:
      - zipline_uploads:/zipline/uploads
      - zipline_public:/zipline/public
    depends_on:
      - postgres-zipline

  accent:
    container_name: accent
    image: mirego/accent
    networks:
      - revproxy
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://postgres:mB56g5FQMiCLzrquSae4znUHxIqp1Y91B@postgres-accent/accent_development
      - CANONICAL_URL=https://accent.genefit.cc
    depends_on:
      - postgres-accent

volumes:
  zipline_pg_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /docker/zipline/pg_data
  accent_pg_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /docker/accent/pg_data
  zipline_uploads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /docker/zipline/uploads
  zipline_public:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /docker/zipline/public

networks:
  revproxy:
    external: true
```

Now once i visit the domain, i see the default page without any option to login or create the first admin account:
![grafik](https://github.com/mirego/accent/assets/94435104/9fdc9ff8-fcb8-40cf-ac19-7c8318120c54)

I would like to know, where i can setup my first admin account or login with existing admin credentials (in which case i also need to know the default login credentials)

Regards,
FuckingToasters
