### ISSUE TITLE
500 Error on Dummy Login – Possibly Missing secret_key_base?

### ISSUE THREAD

**Issue by Oxy-Arnas** [mirego/accent#471]
Hi team 👋

Thanks for the great project! I just cloned the repo and followed the README instructions to start the app with Docker, but I’m running into an issue with the dummy login flow.

The app starts fine and the migrations/seeds run without errors, but when I try to log in via the dummy provider, I get a 500 error. The logs include this:

```
accent           | 11:53:28.432 request_id=GDjwbXBNanwk0f0AAACF [info] GET /auth/dummy/callback
accent           | 11:53:28.444 request_id=GDjwbXBNanwk0f0AAACF [info] Sent 500 in 11ms
accent           | 11:53:28.446 request_id=GDjwbXBNanwk0f0AAACF [error] ** (ArgumentError) cookie store expects conn.secret_key_base to be at least 64 bytes
accent           |     (plug 1.17.0) lib/plug/session/cookie.ex:184: Plug.Session.COOKIE.validate_secret_key_base/1
accent           |     (plug 1.17.0) lib/plug/session/cookie.ex:176: Plug.Session.COOKIE.derive/3
accent           |     (plug 1.17.0) lib/plug/session/cookie.ex:95: Plug.Session.COOKIE.put/4
accent           |     (plug 1.17.0) lib/plug/session.ex:96: anonymous fn/3 in Plug.Session.before_send/2
accent           |     (elixir 1.18.3) lib/enum.ex:2546: Enum."-reduce/3-lists^foldl/2-0-"/3
accent           |     (plug 1.17.0) lib/plug/conn.ex:1878: Plug.Conn.run_before_send/2
accent           |     (plug 1.17.0) lib/plug/conn.ex:445: Plug.Conn.send_resp/1
accent           |     (accent 1.25.1) lib/web/controllers/auth_controller.ex:1: Accent.AuthController.action/2
```

I’m guessing this means secret_key_base is missing or not configured correctly, but I didn’t see anything about it in the README.

Here’s the docker-compose.yml I’m using (slightly adapted from the original):
```
version: '3.7'
services:
  application:
    container_name: accent
    build: .
    ports:
      - 4000:4000
    depends_on:
      - postgresql
    environment:
      - PORT=4000
      - DATABASE_URL=postgres://postgres@postgresql:5432/accent_development
      - DUMMY_LOGIN_ENABLED=1

  postgresql:
    image: postgres:15.6
    container_name: accent-postgres
    environment:
      - POSTGRES_DB=accent_development
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - accent_psql:/var/lib/postgresql/data

volumes:
  accent_psql:
```

Let me know if I’m missing something. Happy to help improve the README once it’s resolved 🙌

Thanks a lot!
